{%- if cookiecutter.ci_template == 'travis' -%}
language: node_js

node_js:
    - "8.4.0"

cache:
    directories:
        - node_modules

install:
    - npm install

script:
    - npm run lint:css
    - npm run lint:js
    - npm run flow
    - npm run test:coveralls
    - npm run build
{%- elif cookiecutter.ci_template == 'gitlab-ci' -%}
cache:
  key: "new_test"
  paths:
    - node_modules/


stages:
  - lint
  - test
  - build


before_script:
  - npm install


lint:
  stage: lint
  script:
    - npm run lint:css
    - npm run lint:js
  allow_failure: false


test:
  stage: test
  script:
    - npm run flow
    - npm run flow stop # explicitly stop the flow-server, because the process sometimes hangs and crashes the CI-runner
    - npm run test:coverage
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'

build:
  stage: build
  script:
    - npm run build
  artifacts:
    name: "${CI_PROJECT_NAME}_${CI_COMMIT_TAG}"
    paths:
      - dist/

  only:
    - tags
  except:
    - dev

  allow_failure: false
{%- endif -%}
